
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 22;
  public static final int STRING_LITERAL = 43;
  public static final int SUM_ASIGN = 18;
  public static final int SUS_ASIGN = 17;
  public static final int CHAR_LITERAL = 42;
  public static final int CLOSE_PARE = 37;
  public static final int LESS_THAN_OR_EQUAL = 26;
  public static final int OPEN_PARE = 36;
  public static final int CONTINUE = 12;
  public static final int INT = 5;
  public static final int FOR = 9;
  public static final int SEMICOLON = 39;
  public static final int NOT = 38;
  public static final int AND = 30;
  public static final int CALLOUT = 13;
  public static final int OR = 31;
  public static final int COMMA = 40;
  public static final int HEX_LITERAL = 44;
  public static final int CLASS = 2;
  public static final int DIFFERENT = 29;
  public static final int ASSIGN = 16;
  public static final int IF = 7;
  public static final int ID = 47;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int RETURN = 10;
  public static final int EQUAL = 28;
  public static final int TRUE = 14;
  public static final int error = 1;
  public static final int PROGRAM = 3;
  public static final int OPEN_BRACE = 32;
  public static final int MOD = 23;
  public static final int CLOSE_BRACKET = 35;
  public static final int BREAK = 11;
  public static final int OPEN_BRACKET = 34;
  public static final int VOID = 4;
  public static final int ERROR = 48;
  public static final int ELSE = 8;
  public static final int HEX_DIGIT = 46;
  public static final int SUS = 20;
  public static final int SUM = 19;
  public static final int CLOSE_BRACE = 33;
  public static final int FALSE = 15;
  public static final int MORE_THAN = 25;
  public static final int LESS_THAN = 24;
  public static final int MORE_THAN_OR_EQUAL = 27;
  public static final int MULTIPLICATION = 21;
  public static final int INT_LITERAL = 45;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "PROGRAM",
  "VOID",
  "INT",
  "BOOLEAN",
  "IF",
  "ELSE",
  "FOR",
  "RETURN",
  "BREAK",
  "CONTINUE",
  "CALLOUT",
  "TRUE",
  "FALSE",
  "ASSIGN",
  "SUS_ASIGN",
  "SUM_ASIGN",
  "SUM",
  "SUS",
  "MULTIPLICATION",
  "DIVIDE",
  "MOD",
  "LESS_THAN",
  "MORE_THAN",
  "LESS_THAN_OR_EQUAL",
  "MORE_THAN_OR_EQUAL",
  "EQUAL",
  "DIFFERENT",
  "AND",
  "OR",
  "OPEN_BRACE",
  "CLOSE_BRACE",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "OPEN_PARE",
  "CLOSE_PARE",
  "NOT",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "CHAR_LITERAL",
  "STRING_LITERAL",
  "HEX_LITERAL",
  "INT_LITERAL",
  "HEX_DIGIT",
  "ID",
  "ERROR"
  };
}

